# Roadmap Data generated from parsed text

ML_ROADMAP = {1: {'days': {1: {'title': 'Python Basics + Linear Algebra I',
                  'topics': ['Python',
                             'Python syntax, indentation',
                             'Variables, data types',
                             'Lists, tuples, sets, dictionaries',
                             'Mutable vs immutable',
                             'Basic I/O',
                             'Math (Linear Algebra)',
                             'Scalars, vectors, matrices',
                             'Vector addition & scalar multiplication',
                             'Matrix shape, transpose',
                             'NumPy',
                             'np.array',
                             'Array shapes, dtype',
                             'Indexing & slicing',
                             'Practice',
                             'Small scripts using lists/dicts',
                             'Create vectors & matrices in NumPy']},
              2: {'title': 'Python Control Flow + Linear Algebra II',
                  'topics': ['Python',
                             'if/else',
                             'for loops, while loops',
                             'break, continue',
                             'List comprehensions',
                             'Math',
                             'Dot product',
                             'Matrix multiplication',
                             'Identity matrix',
                             'NumPy',
                             'np.dot, @',
                             'Broadcasting rules',
                             'np.eye']},
              3: {'title': 'Functions + Linear Algebra III',
                  'topics': ['Python',
                             'Functions',
                             'Arguments, return values',
                             'Default arguments',
                             'Lambda functions',
                             'Math',
                             'Determinant (intuition)',
                             'Inverse matrix (intuition)',
                             'Rank of a matrix',
                             'NumPy',
                             'np.linalg.det',
                             'np.linalg.inv',
                             'np.linalg.matrix_rank']},
              4: {'title': 'OOP Basics + Calculus I',
                  'topics': ['Python',
                             'Classes & objects',
                             '__init__',
                             'Instance vs class variables',
                             'Methods',
                             'Math (Calculus)',
                             'Functions & limits',
                             'Derivatives intuition',
                             'Slope interpretation',
                             'Practice',
                             'Class representing a vector',
                             'Compute derivative numerically']},
              5: {'title': 'OOP Advanced + Calculus II',
                  'topics': ['Python',
                             'Inheritance',
                             'Encapsulation',
                             'Polymorphism',
                             '@property',
                             'Math',
                             'Partial derivatives',
                             'Gradient vector',
                             'Directional derivatives',
                             'NumPy',
                             'Gradient using finite differences']},
              6: {'title': 'File Handling + Pandas I',
                  'topics': ['Python',
                             'Reading/writing files',
                             'OS module',
                             'Path handling',
                             'Pandas',
                             'Series vs DataFrame',
                             'Reading CSV/JSON',
                             'Indexing (loc, iloc)',
                             'Deliverable',
                             'File organizer script']},
              7: {'title': 'Pandas II + Mini Project',
                  'topics': ['Pandas',
                             'Filtering',
                             'Sorting',
                             'Groupby',
                             'Aggregations',
                             'Mini Project',
                             'CSV/JSON parser using classes',
                             'Small EDA notebook',
                             'Matrix ops implemented']}},
     'title': 'Python + Core Math + NumPy/Pandas'},
 2: {'days': {8: {'title': 'Probability Basics',
                  'topics': ['Random variables', 'Sample space', 'PMF, PDF', 'Expectation & variance']},
              9: {'title': 'Distributions',
                  'topics': ['Bernoulli', 'Binomial', 'Normal distribution', 'Law of Large Numbers']},
              10: {'title': 'Bayesian Statistics',
                   'topics': ['Conditional probability', 'Bayes’ theorem', 'Prior, likelihood, posterior']},
              11: {'title': 'Information Theory I', 'topics': ['Entropy', 'Joint entropy', 'Conditional entropy']},
              12: {'title': 'Information Theory II',
                   'topics': ['Cross entropy', 'KL divergence', 'Relation to log-loss']},
              13: {'title': 'Pandas + Visualization',
                   'topics': ['Matplotlib basics', 'Seaborn', 'Histograms, boxplots', 'Correlation heatmaps']},
              14: {'title': 'SQL + Git',
                   'topics': ['SQL',
                              'SELECT, WHERE',
                              'GROUP BY',
                              'HAVING',
                              'JOINs',
                              'Git',
                              'init, clone',
                              'add, commit',
                              'branch',
                              'push to GitHub']}},
     'title': 'Statistics, Information Theory, SQL, Git'},
 3: {'days': {15: {'title': 'ML Fundamentals',
                   'topics': ['Supervised vs unsupervised',
                              'Train/validation/test',
                              'Data leakage',
                              'Bias vs variance']},
              16: {'title': 'Linear Regression Theory',
                   'topics': ['Hypothesis function', 'MSE loss', 'Closed-form solution', 'Gradient descent intuition']},
              17: {'title': 'Linear Regression from Scratch',
                   'topics': ['Cost function', 'Gradient derivation', 'Batch gradient descent', 'Learning rate']},
              18: {'title': 'Logistic Regression Theory',
                   'topics': ['Sigmoid function', 'Log-loss', 'Decision boundary', 'Odds & log-odds']},
              19: {'title': 'Logistic Regression from Scratch',
                   'topics': ['Binary cross-entropy', 'Gradient derivation', 'Training loop', 'Thresholding']},
              20: {'title': 'sklearn Practice',
                   'topics': ['LinearRegression', 'LogisticRegression', 'train_test_split', 'StandardScaler']},
              21: {'title': 'Comparison & Evaluation',
                   'topics': ['Compare scratch vs sklearn', 'Accuracy vs loss curves', 'Overfitting detection']}},
     'title': 'ML Basics + Linear & Logistic Regression'},
 4: {'days': {22: {'title': 'Decision Trees',
                   'topics': ['CART algorithm', 'Gini impurity', 'Entropy', 'Splitting criteria']},
              23: {'title': 'Decision Tree Implementation',
                   'topics': ['Recursive splitting', 'Stopping criteria', 'Depth vs bias-variance']},
              24: {'title': 'Random Forests', 'topics': ['Bagging', 'Feature randomness', 'Hyperparameters']},
              25: {'title': 'Evaluation Metrics', 'topics': ['Confusion matrix', 'Precision, recall', 'F1-score']},
              26: {'title': 'ROC & PR Curves', 'topics': ['ROC curve', 'AUC', 'Precision-Recall tradeoff']},
              27: {'title': 'Project 1 (Loan Default)', 'topics': ['EDA', 'Feature cleaning', 'Model training']},
              28: {'title': 'Project 1 Wrap-up', 'topics': ['Model comparison', 'Final metrics', 'README + GitHub']}},
     'title': 'Trees, Ensembles, Metrics + Project 1'},
 5: {'days': {29: {'title': 'Gradient Boosting Theory',
                   'topics': ['Boosting intuition', 'Weak learners', 'Residual fitting']},
              30: {'title': 'XGBoost', 'topics': ['Tree boosting', 'Learning rate', 'Regularization']},
              31: {'title': 'LightGBM & CatBoost', 'topics': ['Leaf-wise growth', 'Categorical handling']},
              32: {'title': 'SVM', 'topics': ['Maximum margin', 'Hard vs soft margin', 'Kernel trick']},
              33: {'title': 'KNN', 'topics': ['Distance metrics', 'Curse of dimensionality']},
              34: {'title': 'Clustering Basics', 'topics': ['KMeans', 'DBSCAN', 'Hierarchical clustering']},
              35: {'title': 'PCA', 'topics': ['Variance maximization', 'Eigenvalues/vectors', 'Explained variance']}},
     'title': 'Advanced Algorithms'},
 6: {'days': {36: {'title': 'Advanced Metrics', 'topics': ['ROC-AUC for imbalance', 'PR curves', 'Calibration']},
              37: {'title': 'Model Interpretability', 'topics': ['Permutation importance', 'SHAP intuition']},
              38: {'title': 'Clustering Project EDA', 'topics': ['Scaling', 'Feature selection']},
              39: {'title': 'KMeans Project', 'topics': ['Elbow method', 'Silhouette score']},
              40: {'title': 'DBSCAN', 'topics': ['Density-based clustering', 'Parameter tuning']},
              41: {'title': 'Cluster Profiling', 'topics': ['Mean profiles', 'Business interpretation']},
              42: {'title': 'Project Write-up', 'topics': ['Visualizations', 'README']}},
     'title': 'Evaluation + Clustering Project'},
 7: {'days': {43: {'title': 'Missing Data', 'topics': ['Mean/median imputation', 'KNN imputation']},
              44: {'title': 'Outliers', 'topics': ['IQR', 'Z-score', 'Winsorization']},
              45: {'title': 'Encoding', 'topics': ['One-hot', 'Target encoding', 'Ordinal encoding']},
              46: {'title': 'Scaling', 'topics': ['StandardScaler', 'MinMaxScaler', 'RobustScaler']},
              47: {'title': 'Imbalanced Learning', 'topics': ['Class weights', 'SMOTE', 'Under/oversampling']},
              48: {'title': 'Fraud Project EDA', 'topics': ['Class imbalance analysis']},
              49: {'title': 'Fraud Preprocessing Pipeline', 'topics': ['sklearn pipelines']}},
     'title': 'Feature Engineering + Fraud Project'},
 8: {'days': {50: {'title': 'DVC Basics', 'topics': ['Init DVC', 'Track datasets', 'Remote storage']},
              51: {'title': 'DVC Pipelines', 'topics': ['Stages', 'Reproducibility']},
              52: {'title': 'MLflow Basics', 'topics': ['Tracking experiments', 'Logging params/metrics']},
              53: {'title': 'MLflow Model Registry', 'topics': ['Save models', 'Versioning']},
              54: {'title': 'FastAPI Basics', 'topics': ['Endpoints', 'Request/response models']},
              55: {'title': 'Model Serving', 'topics': ['/predict endpoint', 'Input validation']},
              56: {'title': 'Integration', 'topics': ['DVC + MLflow + FastAPI']}},
     'title': 'MLOps Foundations'},
 9: {'days': {57: {'title': 'Perceptron & Neural Network Basics',
                   'topics': ['Biological neuron vs artificial neuron',
                              'Perceptron model',
                              'Weighted sum + bias',
                              'Activation function intuition',
                              'Linear separability',
                              'Limitations of perceptron']},
              58: {'title': 'Activation Functions',
                   'topics': ['Sigmoid',
                              'Shape',
                              'Vanishing gradient',
                              'Tanh',
                              'ReLU',
                              'Leaky ReLU',
                              'Activation function selection criteria']},
              59: {'title': 'Loss Functions',
                   'topics': ['Regression losses',
                              'MSE',
                              'MAE',
                              'Classification losses',
                              'Binary cross-entropy',
                              'Categorical cross-entropy',
                              'Relation to likelihood']},
              60: {'title': 'Forward Propagation',
                   'topics': ['Layer-wise computation',
                              'Matrix formulation of forward pass',
                              'Batch processing',
                              'Numerical stability issues']},
              61: {'title': 'Backpropagation Theory',
                   'topics': ['Chain rule recap',
                              'Gradient flow',
                              'Error propagation',
                              'Why backprop works',
                              'Computational graph intuition']},
              62: {'title': 'Gradient Descent Variants',
                   'topics': ['Batch Gradient Descent',
                              'Stochastic Gradient Descent',
                              'Mini-batch Gradient Descent',
                              'Learning rate effects',
                              'Convergence behavior']},
              63: {'title': 'NumPy NN from Scratch',
                   'topics': ['2-layer neural network',
                              'Forward pass implementation',
                              'Backward pass (manual gradients)',
                              'Weight updates',
                              'Loss curve visualization']}},
     'title': 'Neural Network Theory + NumPy Implementation'},
 10: {'days': {64: {'title': 'PyTorch Basics',
                    'topics': ['Tensors', 'Tensor shapes', 'Broadcasting', 'CPU vs GPU tensors', '.to(device)']},
               65: {'title': 'Autograd',
                    'topics': ['Computational graphs',
                               'requires_grad',
                               '.backward()',
                               'Gradient accumulation',
                               'detach()']},
               66: {'title': 'nn.Module & Layers',
                    'topics': ['nn.Module',
                               'nn.Linear',
                               'Model class structure',
                               'Forward method',
                               'Parameter inspection']},
               67: {'title': 'Training Loop Pattern',
                    'topics': ['Dataset vs DataLoader',
                               'Batching',
                               'Training vs evaluation mode',
                               'Loss computation',
                               'Optimizer step',
                               'Zeroing gradients']},
               68: {'title': 'Optimizers', 'topics': ['SGD', 'Momentum', 'RMSprop', 'Adam', 'When to use which']},
               69: {'title': 'Regularization',
                    'topics': ['L1 vs L2', 'Weight decay', 'Dropout', 'Early stopping', 'Batch normalization']},
               70: {'title': 'CNN Fundamentals',
                    'topics': ['Convolution operation', 'Kernels & filters', 'Stride', 'Padding', 'Feature maps']}},
      'title': 'PyTorch Fundamentals + CNN Basics'},
 11: {'days': {71: {'title': 'Pooling & CNN Architecture',
                    'topics': ['Max pooling', 'Average pooling', 'Spatial invariance', 'Typical CNN block structure']},
               72: {'title': 'Simple CNN Implementation',
                    'topics': ['Conv → ReLU → Pool blocks',
                               'Fully connected layers',
                               'Softmax output',
                               'Loss & optimizer']},
               73: {'title': 'CIFAR-10 Dataset',
                    'topics': ['Dataset loading', 'Normalization', 'Train/validation split', 'Class distribution']},
               74: {'title': 'Training Baseline CNN',
                    'topics': ['Epoch loops', 'Accuracy tracking', 'Loss curves', 'Overfitting signs']},
               75: {'title': 'Data Augmentation',
                    'topics': ['Random crop', 'Horizontal flip', 'Color jitter', 'Why augmentation works']},
               76: {'title': 'CNN Hyperparameter Tuning',
                    'topics': ['Learning rate', 'Batch size', 'Depth vs width', 'Regularization tuning']},
               77: {'title': 'Model Evaluation', 'topics': ['Accuracy', 'Confusion matrix', 'Per-class performance']}},
      'title': 'CNN Project (CIFAR-10)'},
 12: {'days': {78: {'title': 'Transfer Learning Theory',
                    'topics': ['Feature reuse', 'Freezing layers', 'Fine-tuning strategy']},
               79: {'title': 'Pretrained CNNs',
                    'topics': ['ResNet architecture (conceptual)',
                               'Loading pretrained weights',
                               'Modifying classifier head']},
               80: {'title': 'Fine-Tuning ResNet',
                    'topics': ['Freezing backbone', 'Training head', 'Partial unfreezing']},
               81: {'title': 'Model Saving & Loading', 'topics': ['state_dict', 'Checkpoints', 'Best-model saving']},
               82: {'title': 'FastAPI for DL Models',
                    'topics': ['Request schema', 'Image preprocessing', 'Model inference endpoint']},
               83: {'title': 'Optional Dockerization', 'topics': ['Dockerfile', 'Image build', 'Container run']},
               84: {'title': 'Project Documentation', 'topics': ['README', 'Results', 'Architecture diagram']}},
      'title': 'Transfer Learning + Deployment'},
 13: {'days': {85: {'title': 'Attention Mechanism',
                    'topics': ['Query, Key, Value', 'Dot-product attention', 'Scaling factor']},
               86: {'title': 'Self-Attention',
                    'topics': ['Token interactions', 'Contextual representations', 'Attention matrix visualization']},
               87: {'title': 'Multi-Head Attention',
                    'topics': ['Parallel attention heads', 'Concatenation', 'Projection layers']},
               88: {'title': 'Positional Encoding',
                    'topics': ['Why position matters', 'Sinusoidal encoding', 'Learned embeddings']},
               89: {'title': 'Transformer Architecture',
                    'topics': ['Encoder block', 'Decoder block', 'Residual connections', 'Layer normalization']},
               90: {'title': 'Model Families',
                    'topics': ['Encoder-only (BERT)', 'Decoder-only (GPT)', 'Encoder-decoder (T5)']},
               91: {'title': 'Hugging Face Basics', 'topics': ['Tokenizers', 'AutoModel', 'AutoTokenizer']}},
      'title': 'Transformer Theory + HF Basics'},
 14: {'days': {92: {'title': 'Text Classification Pipeline',
                    'topics': ['Tokenization', 'Attention masks', 'Padding & truncation']},
               93: {'title': 'Fine-Tuning BERT',
                    'topics': ['Loss computation', 'Optimizer', 'Learning rate scheduling']},
               94: {'title': 'Evaluation Metrics', 'topics': ['Accuracy', 'Precision, recall, F1', 'Confusion matrix']},
               95: {'title': 'Regularization in Transformers', 'topics': ['Dropout', 'Weight decay', 'Early stopping']},
               96: {'title': 'Error Analysis', 'topics': ['Misclassified examples', 'Bias analysis']},
               97: {'title': 'Model Saving', 'topics': ['Hugging Face save/load', 'Inference pipeline']},
               98: {'title': 'Project Cleanup', 'topics': ['Code refactor', 'README']}},
      'title': 'BERT Fine-Tuning'},
 15: {'days': {99: {'title': 'Embeddings Theory', 'topics': ['Word vs sentence embeddings', 'Semantic similarity']},
               100: {'title': 'SentenceTransformers', 'topics': ['Model selection', 'Embedding generation']},
               101: {'title': 'Similarity Metrics', 'topics': ['Cosine similarity', 'Euclidean distance']},
               102: {'title': 'Semantic Search', 'topics': ['Top-k retrieval', 'Ranking']},
               103: {'title': 'FAISS Basics', 'topics': ['Index types', 'Building an index', 'Querying']},
               104: {'title': 'Search Evaluation', 'topics': ['Precision@k', 'Recall@k']},
               105: {'title': 'Mini Project', 'topics': ['Document embedding pipeline']}},
      'title': 'Embeddings & Semantic Search'},
 16: {'days': {106: {'title': 'System Design', 'topics': ['Retrieval + classification flow']},
               107: {'title': 'FastAPI Search Endpoint', 'topics': ['/search', 'Query handling']},
               108: {'title': 'Classification Endpoint', 'topics': ['/classify']},
               109: {'title': 'Combined Pipeline', 'topics': ['Retrieve → classify']},
               110: {'title': 'Performance Optimization', 'topics': ['Batch inference', 'Caching']},
               111: {'title': 'Documentation', 'topics': ['Architecture', 'Trade-offs']},
               112: {'title': 'Demo & Cleanup', 'topics': ['Example workflows', 'Screenshots']}},
      'title': 'Integration + API'},
 17: {'days': {113: {'title': 'GPT Architecture', 'topics': ['Decoder-only transformer', 'Autoregressive modeling']},
               114: {'title': 'Sampling Strategies', 'topics': ['Greedy decoding', 'Temperature', 'Top-k', 'Top-p']},
               115: {'title': 'Prompt Engineering', 'topics': ['Zero-shot', 'Few-shot', 'Role prompting']},
               116: {'title': 'Prompt Patterns', 'topics': ['Chain-of-thought', 'ReAct', 'Self-consistency']},
               117: {'title': 'API Usage', 'topics': ['OpenAI / HF APIs', 'Token limits', 'Cost awareness']},
               118: {'title': 'Small LLM Apps', 'topics': ['Summarization', 'Q&A', 'Classification']},
               119: {'title': 'Prompt Experiments', 'topics': ['Prompt comparison', 'Logging outputs']}},
      'title': 'LLM Fundamentals'},
 18: {'days': {120: {'title': 'RAG Architecture', 'topics': ['Retrieval vs generation', 'Failure modes']},
               121: {'title': 'Document Chunking', 'topics': ['Chunk size', 'Overlap', 'Metadata']},
               122: {'title': 'Embedding Pipeline', 'topics': ['Batch embedding', 'Storage']},
               123: {'title': 'Vector Databases', 'topics': ['FAISS', 'ChromaDB']},
               124: {'title': 'RAG Prompting', 'topics': ['Context stuffing', 'Instruction design']},
               125: {'title': 'FastAPI RAG Service', 'topics': ['/ask endpoint']},
               126: {'title': 'Evaluation', 'topics': ['Faithfulness', 'Relevance']}},
      'title': 'RAG Systems'},
 19: {'days': {127: {'title': 'Fine-Tuning Theory', 'topics': ['Full fine-tuning vs PEFT', 'LoRA intuition']},
               128: {'title': 'Dataset Preparation', 'topics': ['Instruction format', 'Train/validation split']},
               129: {'title': 'LoRA Implementation', 'topics': ['Adapter layers', 'Training config']},
               130: {'title': 'Training & Monitoring', 'topics': ['Loss curves', 'Overfitting']},
               131: {'title': 'Evaluation', 'topics': ['Base vs fine-tuned', 'Manual inspection']},
               132: {'title': 'Save & Load', 'topics': ['Adapter weights']},
               133: {'title': 'Documentation', 'topics': ['Findings', 'Limitations']}},
      'title': 'Parameter-Efficient Fine-Tuning'},
 20: {'days': {134: {'title': 'LLM Evaluation', 'topics': ['Rubric-based scoring', 'Automated checks']},
               135: {'title': 'Logging', 'topics': ['Prompts', 'Responses', 'Latency']},
               136: {'title': 'Cost Tracking', 'topics': ['Token usage', 'API cost estimation']},
               137: {'title': 'Prompt Versioning', 'topics': ['Experiment tracking']},
               138: {'title': 'Dashboards', 'topics': ['Simple plots', 'Metrics tracking']},
               139: {'title': 'Service Hardening', 'topics': ['Timeouts', 'Error handling']},
               140: {'title': 'Month Review', 'topics': ['Lessons learned', 'Improvements']}},
      'title': 'LLMOps'},
 21: {'days': {141: {'title': 'Agent Concepts', 'topics': ['Planning', 'Tool use', 'Memory']},
               142: {'title': 'ReAct Pattern', 'topics': ['Thought', 'Action', 'Observation']},
               143: {'title': 'Tool Calling', 'topics': ['Calculator', 'Search', 'Retrieval']},
               144: {'title': 'Memory', 'topics': ['Short-term', 'Long-term', 'Vector memory']},
               145: {'title': 'Single Agent Project', 'topics': ['Task execution loop']},
               146: {'title': 'Prompt Refinement', 'topics': ['Failure handling']},
               147: {'title': 'Agent Evaluation', 'topics': ['Task success rate']}},
      'title': 'Agentic AI'},
 22: {'days': {148: {'title': 'Multi-Agent Design', 'topics': ['Roles', 'Responsibilities']},
               149: {'title': 'Manager/Worker Pattern', 'topics': ['Task delegation']},
               150: {'title': 'Researcher Agent', 'topics': ['Retrieval', 'Summarization']},
               151: {'title': 'Critic Agent', 'topics': ['Quality checks', 'Feedback']},
               152: {'title': 'Writer Agent', 'topics': ['Report generation']},
               153: {'title': 'Coordination Logic', 'topics': ['Turn-taking', 'Stopping criteria']},
               154: {'title': 'System Integration', 'topics': ['Full pipeline test']}},
      'title': 'Multi-Agent Systems'},
 23: {'days': {}, 'title': 'CAPSTONE'},
 24: {'days': {155: {'title': 'Capstone Planning', 'topics': ['Problem definition', 'Success criteria']},
               156: {'title': 'Architecture Design', 'topics': ['Components', 'Data flow']},
               157: {'title': 'RAG Integration', 'topics': ['Knowledge base', 'Retrieval tuning']},
               158: {'title': 'Agent Orchestration', 'topics': ['Multi-step reasoning']},
               159: {'title': 'Backend Implementation', 'topics': ['FastAPI endpoints']},
               160: {'title': 'UI Layer', 'topics': ['Streamlit / Gradio']},
               161: {'title': 'Logging & Monitoring', 'topics': ['Metrics', 'Errors']},
               162: {'title': 'Configuration', 'topics': ['Env vars', 'Secrets']},
               163: {'title': 'Testing', 'topics': ['Smoke tests', 'Edge cases']},
               164: {'title': 'Performance Review', 'topics': ['Latency', 'Cost']},
               165: {'title': 'Documentation', 'topics': ['README', 'Architecture diagram']},
               166: {'title': 'Demo Prep', 'topics': ['Example workflows']},
               167: {'title': 'Final Polish', 'topics': ['Refactoring', 'Cleanup']},
               168: {'title': 'Capstone Delivery', 'topics': ['GitHub final push', 'Demo video', 'Self-review']}},
       'title': 'CAPSTONE'}}

# --- Defined Projects for the Projects Tab ---
ML_PROJECTS = {
    7: {
        "title": "File Organizer & Parser Script",
        "description": "Build a robust Python script to organize files in a directory and parse CSV/JSON data.",
        "features": [
            "Sort files by extension into folders",
            "Parse a CSV file using 'csv' module only",
            "Parse a JSON file and print keys",
            "Object-Oriented Design (Class-based)"
        ]
    },
    27: {
        "title": "Loan Default Prediction (Project 1)",
        "description": "End-to-end classification project to predict if a borrower will default.",
        "features": [
            "EDA on Loan Dataset (histograms, correlations)",
            "Data Cleaning (missing values, outliers)",
            "Train Decision Tree & Random Forest models",
            "Evaluate with ROC-AUC and F1-score"
        ]
    },
    39: {
        "title": "Customer Segmentation (Clustering)",
        "description": "Unsupervised learning project to group customers based on purchasing behavior.",
        "features": [
            "Feature Scaling (StandardScaler)",
            "K-Means Clustering with Elbow Method",
            "Visualize clusters (2D PCA or Pairplot)",
            "Interpret cluster characteristics"
        ]
    },
    48: {
        "title": "Fraud Detection System",
        "description": "Handle highly imbalanced data to detect fraudulent transactions.",
        "features": [
            "Handle Class Imbalance (SMOTE or Class Weights)",
            "Feature Engineering (time of day, amount scaling)",
            "Train Gradient Boosting Model (XGBoost/LightGBM)",
            "Precision-Recall Curve analysis"
        ]
    },
    56: {
        "title": "MLOps End-to-End Pipeline",
        "description": "Integrate previous models into a reproducible pipeline.",
        "features": [
            "Track data with DVC",
            "Log experiments with MLflow",
            "Serve model via FastAPI endpoint",
            "Input validation using Pydantic"
        ]
    },
    63: {
        "title": "Neural Network from Scratch",
        "description": "Implement a 2-layer Neural Network using only NumPy.",
        "features": [
            "Forward propagation (matrix multiplication)",
            "Backpropagation (manual gradient derivation)",
            "Training loop with SGD",
            "Visualize Loss vs Epochs"
        ]
    },
    73: {
        "title": "CIFAR-10 Image Classifier",
        "description": "Build and train a Convolutional Neural Network (CNN) in PyTorch.",
        "features": [
            "Custom Dataset/DataLoader for CIFAR-10",
            "CNN Architecture (Conv2d, MaxPool, ReLU)",
            "Training Loop with GPU support",
            "Data Augmentation transforms"
        ]
    },
    80: {
        "title": "Transfer Learning with ResNet",
        "description": "Fine-tune a pre-trained ResNet model for a custom classification task.",
        "features": [
            "Load pre-trained ResNet18/50",
            "Freeze feature extractor layers",
            "Replace and train the classifier head",
            "Compare accuracy vs scratch model"
        ]
    },
    93: {
        "title": "BERT Text Classifier",
        "description": "Fine-tune a BERT model for sentiment analysis or text classification.",
        "features": [
            "Hugging Face Tokenizer usage",
            "Fine-tuning loop with PyTorch/Trainer",
            "Evaluation on Test Set",
            "Save and Reload model for inference"
        ]
    },
    105: {
        "title": "Semantic Search Engine",
        "description": "Build a search tool that understands meaning, not just keywords.",
        "features": [
            "Generate embeddings with SentenceTransformers",
            "Store embeddings in FAISS index",
            "Query function returning top-k results",
            "Simple UI or CLI for search"
        ]
    },
    125: {
        "title": "RAG Q&A System",
        "description": "Retrieval-Augmented Generation system using an LLM.",
        "features": [
            "Document Chunking and Embedding",
            "Vector DB retrieval",
            "Prompt Engineering for LLM context",
            "FastAPI endpoint for Questions"
        ]
    },
    155: {
        "title": "Final Capstone: Multi-Agent AI",
        "description": "A complex system integrating RAG, Agents, and a UI.",
        "features": [
            "Architecture Design Document",
            "Orchestrator Agent + Worker Agents",
            "Full-stack UI (Streamlit)",
            "Video Demo & GitHub Documentation"
        ]
    }
}